products_data = [
    {
        "id": 1,
        "Name": "Product 1",
        "Description": "This is Product 1",
        "Price": 10.99,
        "Category": "Category 1",
        "Image URL": "https://example.com/product1.jpg",
        "CreatedAt": "2023-08-04T12:34:56.789Z",
    },
    {
        "id": 2,
        "Name": "Product 2",
        "Description": "This is Product 2",
        "Price": 19.99,
        "Category": "Category 2",
        "Image URL": "https://example.com/product2.jpg",
        "CreatedAt": "2023-08-04T12:45:23.456Z",
    },
    {
        "id": 3,
        "Name": "Product 3",
        "Description": "This is Product 3",
        "Price": 5.99,
        "Category": "Category 1",
        "Image URL": "https://example.com/product3.jpg",
        "CreatedAt": "2023-08-04T13:10:00.123Z",
    },
    {
        "id": 4,
        "Name": "Product 4",
        "Description": "This is Product 4",
        "Price": 29.99,
        "Category": "Category 3",
        "Image URL": "https://example.com/product4.jpg",
        "CreatedAt": "2023-08-04T13:22:47.890Z",
    },
    {
        "id": 5,
        "Name": "Product 5",
        "Description": "This is Product 5",
        "Price": 15.49,
        "Category": "Category 2",
        "Image URL": "https://example.com/product5.jpg",
        "CreatedAt": "2023-08-04T14:05:11.567Z",
    },
]