name: checks

on: [push]

jobs:
  testing-linting:
    name: Testing
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        working-directory: ./backend
        run: |
          echo "$APP_ENV_CONTENT" > app.env
          echo "$DB_ENV_CONTENT" > db.env
          docker-compose run --rm app sh -c "python manage.py test"
      - name: Linting
        working-directory: ./backend
        run: |
          docker-compose run --rm app sh -c "python manage.py flake8"
